# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-04 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='caIssuers',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='crlDistributionPoints',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='issuer_commonName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='issuer_organizaionUnitName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='issuer_organizationName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='issuer_serialNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_businessCategory',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_commonName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_localityName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_organizationName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_postalCode',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_serialNumber',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_stateOrProvinceName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subject_streetAddress',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
