# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 01:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0002_auto_20170104_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='issuer_notAfter',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='issuer_notBefore',
            field=models.DateTimeField(null=True),
        ),
    ]
