# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 02:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0004_auto_20170105_0244'),
    ]

    operations = [
        migrations.AddField(
            model_name='certinfo',
            name='version',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
