# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 13:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0005_certinfo_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectAltName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altName', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 13, 28, 2, 63834, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 13, 28, 2, 64459, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='certinfo',
            name='subjectAltName',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ssl_watcher.SubjectAltName'),
        ),
    ]
