# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 15:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0006_auto_20170105_1328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 33, 23, 109513, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='subjectAltName',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 33, 23, 110062, tzinfo=utc)),
        ),
    ]
