# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 15:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0007_auto_20170105_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 41, 38, 516647)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 41, 38, 517180)),
        ),
    ]
