# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 15:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0010_auto_20170105_1545'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certinfo',
            old_name='issuer_serialNumber',
            new_name='serialNumber',
        ),
        migrations.RemoveField(
            model_name='certinfo',
            name='subject_organizationName',
        ),
        migrations.AddField(
            model_name='certinfo',
            name='subject_organizationalName',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 54, 15, 658093, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 54, 15, 659079, tzinfo=utc)),
        ),
    ]
