# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 15:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0011_auto_20170105_1554'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certinfo',
            old_name='issuer_organizaionUnitName',
            new_name='issuer_organizaionalUnitName',
        ),
        migrations.RenameField(
            model_name='certinfo',
            old_name='subject_organizationalName',
            new_name='subject_organizationName',
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 55, 9, 980842, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 15, 55, 9, 981545, tzinfo=utc)),
        ),
    ]
