# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0012_auto_20170105_1555'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certinfo',
            old_name='issuer_organizaionalUnitName',
            new_name='issuer_organizationalUnitName',
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 16, 5, 21, 393328, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 16, 5, 21, 393820, tzinfo=utc)),
        ),
    ]
