# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-05 21:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0014_auto_20170105_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 21, 37, 30, 756141, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 5, 21, 37, 30, 756663, tzinfo=utc)),
        ),
    ]
