# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 08:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0017_auto_20170107_0829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 8, 35, 56, 106492, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 8, 35, 56, 107135, tzinfo=utc)),
        ),
    ]
