# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-01-07 09:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ssl_watcher', '0018_auto_20170107_0835'),
    ]

    operations = [
        migrations.AddField(
            model_name='certinfo',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='certinfo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 9, 20, 15, 545430, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='filemodel',
            name='uploaded_at',
            field=models.DateTimeField(default=datetime.datetime(2017, 1, 7, 9, 20, 15, 546089, tzinfo=utc)),
        ),
    ]
